//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBudget.OperationsLoading {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBudget.OperationsLoading.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Obsolete] BGZ BNP Paribas operations (CSV).
        /// </summary>
        internal static string BgzBnpParibasName {
            get {
                return ResourceManager.GetString("BgzBnpParibasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNPParibas operations (XLS / Excel) (.xlsx)|*.xlsx.
        /// </summary>
        internal static string BnpParibasXslxFilter {
            get {
                return ResourceManager.GetString("BnpParibasXslxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNPParibas operations (XLS / Excel).
        /// </summary>
        internal static string BnpParibasXslxName {
            get {
                return ResourceManager.GetString("BnpParibasXslxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.csv)|*.csv.
        /// </summary>
        internal static string CsvFilter {
            get {
                return ResourceManager.GetString("CsvFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millenium operations (.csv)|*.csv.
        /// </summary>
        internal static string MilleniumFilter {
            get {
                return ResourceManager.GetString("MilleniumFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millenium operations CSV.
        /// </summary>
        internal static string MilleniumName {
            get {
                return ResourceManager.GetString("MilleniumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No credit card number was found..
        /// </summary>
        internal static string NoCreditCardFound {
            get {
                return ResourceManager.GetString("NoCreditCardFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pko BP cleared CreditCard operations (.pdf)|*.pdf.
        /// </summary>
        internal static string PkoBpCardClearedFilter {
            get {
                return ResourceManager.GetString("PkoBpCardClearedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pko BP cleared CreditCard operations.
        /// </summary>
        internal static string PkoBpCardClearedName {
            get {
                return ResourceManager.GetString("PkoBpCardClearedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Obsolete} Pko BP uncleared CreditCard operations (.txt)|*.txt.
        /// </summary>
        internal static string PkoBpCardFilter {
            get {
                return ResourceManager.GetString("PkoBpCardFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Obsolete} Pko BP uncleared CreditCard operations.
        /// </summary>
        internal static string PkoBpCardName {
            get {
                return ResourceManager.GetString("PkoBpCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pko BP operations (.xml)|*.xml.
        /// </summary>
        internal static string PkoBpFilter {
            get {
                return ResourceManager.GetString("PkoBpFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pko BP operations (XML).
        /// </summary>
        internal static string PkoBpName {
            get {
                return ResourceManager.GetString("PkoBpName", resourceCulture);
            }
        }
    }
}
