//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBudget.OperationsLoading.Tests.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DemoFiles {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoFiles() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBudget.OperationsLoading.Tests.Resources.DemoFiles", typeof(DemoFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string MilleniumParser_Family2026_03 {
            get {
                return ResourceManager.GetString("MilleniumParser_Family2026_03", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string MilleniumParser_Family2026_04 {
            get {
                return ResourceManager.GetString("MilleniumParser_Family2026_04", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string MilleniumParser_Family2026_05 {
            get {
                return ResourceManager.GetString("MilleniumParser_Family2026_05", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string MilleniumParser_Family2026_06 {
            get {
                return ResourceManager.GetString("MilleniumParser_Family2026_06", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string MilleniumParser_Family2026_07 {
            get {
                return ResourceManager.GetString("MilleniumParser_Family2026_07", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string MilleniumParser_Family2026_08 {
            get {
                return ResourceManager.GetString("MilleniumParser_Family2026_08", resourceCulture);
            }
        }
    }
}
