//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBudget.OperationsLoading.Tests.Resources {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DemoFiles {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoFiles() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBudget.OperationsLoading.Tests.Resources.DemoFiles", typeof(DemoFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static byte[] BNP_TestOperations_2026_03 => (byte[])ResourceManager.GetObject("BNP_TestOperations_2026_03", resourceCulture);
        internal static byte[] BNP_TestOperations_2026_04 => (byte[])ResourceManager.GetObject("BNP_TestOperations_2026_04", resourceCulture);
        internal static byte[] BNP_TestOperations_2026_05 => (byte[])ResourceManager.GetObject("BNP_TestOperations_2026_05", resourceCulture);
        internal static byte[] BNP_TestOperations_2026_06 => (byte[])ResourceManager.GetObject("BNP_TestOperations_2026_06", resourceCulture);
        internal static byte[] BNP_TestOperations_2026_07 => (byte[])ResourceManager.GetObject("BNP_TestOperations_2026_07", resourceCulture);
        internal static byte[] BNP_TestOperations_2026_08 => (byte[])ResourceManager.GetObject("BNP_TestOperations_2026_08", resourceCulture);

        internal static string MilleniumParser_Family2026_03 => ResourceManager.GetString("MilleniumParser_Family2026_03", resourceCulture);
        internal static string MilleniumParser_Family2026_04 => ResourceManager.GetString("MilleniumParser_Family2026_04", resourceCulture);
        internal static string MilleniumParser_Family2026_05 => ResourceManager.GetString("MilleniumParser_Family2026_05", resourceCulture);
        internal static string MilleniumParser_Family2026_06 => ResourceManager.GetString("MilleniumParser_Family2026_06", resourceCulture);
        internal static string MilleniumParser_Family2026_07 => ResourceManager.GetString("MilleniumParser_Family2026_07", resourceCulture);
        internal static string MilleniumParser_Family2026_08 => ResourceManager.GetString("MilleniumParser_Family2026_08", resourceCulture);
    }
}
