//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBudget.UI.Operations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBudget.UI.Operations.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply rules.
        /// </summary>
        internal static string ApplyRules {
            get {
                return ResourceManager.GetString("ApplyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear categories.
        /// </summary>
        internal static string ClearCategories {
            get {
                return ResourceManager.GetString("ClearCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create rule.
        /// </summary>
        internal static string ContextMenu_CreateRule {
            get {
                return ResourceManager.GetString("ContextMenu_CreateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  contains .
        /// </summary>
        internal static string LabelContains {
            get {
                return ResourceManager.GetString("LabelContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string LabelField {
            get {
                return ResourceManager.GetString("LabelField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load time.
        /// </summary>
        internal static string LoadTime {
            get {
                return ResourceManager.GetString("LoadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operation selected.
        /// </summary>
        internal static string OperationNotLoaded {
            get {
                return ResourceManager.GetString("OperationNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        internal static string ShouldSaveCaption {
            get {
                return ResourceManager.GetString("ShouldSaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations has changed, would you like to save changes?.
        /// </summary>
        internal static string ShouldSaveText {
            get {
                return ResourceManager.GetString("ShouldSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall sum.
        /// </summary>
        internal static string SumText {
            get {
                return ResourceManager.GetString("SumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string TextBlockFilter {
            get {
                return ResourceManager.GetString("TextBlockFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string TextBlockGroup {
            get {
                return ResourceManager.GetString("TextBlockGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclassified.
        /// </summary>
        internal static string UnclassifiedDefaultText {
            get {
                return ResourceManager.GetString("UnclassifiedDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string WatermarkFilter {
            get {
                return ResourceManager.GetString("WatermarkFilter", resourceCulture);
            }
        }
    }
}
