//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBudget.Core.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBudget.Core.Model.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BankAccount_Description {
            get {
                return ResourceManager.GetString("BankAccount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string BankAccount_Name {
            get {
                return ResourceManager.GetString("BankAccount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string BankAccount_Number {
            get {
                return ResourceManager.GetString("BankAccount_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string BankOperation_Amount {
            get {
                return ResourceManager.GetString("BankOperation_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account.
        /// </summary>
        public static string BankOperation_BankAccount {
            get {
                return ResourceManager.GetString("BankOperation_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string BankOperation_Card {
            get {
                return ResourceManager.GetString("BankOperation_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string BankOperation_Category {
            get {
                return ResourceManager.GetString("BankOperation_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BankOperation_Description {
            get {
                return ResourceManager.GetString("BankOperation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending balance.
        /// </summary>
        public static string BankOperation_EndingBalance {
            get {
                return ResourceManager.GetString("BankOperation_EndingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution date.
        /// </summary>
        public static string BankOperation_ExecutionDate {
            get {
                return ResourceManager.GetString("BankOperation_ExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string BankOperation_LpOnStatement {
            get {
                return ResourceManager.GetString("BankOperation_LpOnStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        public static string BankOperation_OrderDate {
            get {
                return ResourceManager.GetString("BankOperation_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub category.
        /// </summary>
        public static string BankOperation_SubCategory {
            get {
                return ResourceManager.GetString("BankOperation_SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string BankOperation_Title {
            get {
                return ResourceManager.GetString("BankOperation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string BankOperation_Type {
            get {
                return ResourceManager.GetString("BankOperation_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string BankOperationType_Name {
            get {
                return ResourceManager.GetString("BankOperationType_Name", resourceCulture);
            }
        }
    }
}
